import type { IconProps } from "@phosphor-icons/react";
import {
  AddressBook as AddressBookIcon,
  Airplane as AirplaneIcon,
  Alarm as AlarmIcon,
  ArchiveBox as ArchiveBoxIcon,
  Armchair as ArmchairIcon,
  ArrowBendDownLeft as ArrowBendDownLeftIcon,
  ArrowBendDownRight as ArrowBendDownRightIcon,
  ArrowBendUpLeft as ArrowBendUpLeftIcon,
  ArrowBendUpRight as ArrowBendUpRightIcon,
  ArrowCircleDown as ArrowCircleDownIcon,
  ArrowCircleLeft as ArrowCircleLeftIcon,
  ArrowCircleRight as ArrowCircleRightIcon,
  ArrowCircleUp as ArrowCircleUpIcon,
  ArrowClockwise as ArrowClockwiseIcon,
  ArrowCounterClockwise as ArrowCounterClockwiseIcon,
  ArrowDown as ArrowDownIcon,
  ArrowElbowDownLeft as ArrowElbowDownLeftIcon,
  ArrowElbowDownRight as ArrowElbowDownRightIcon,
  ArrowElbowLeft as ArrowElbowLeftIcon,
  ArrowElbowRight as ArrowElbowRightIcon,
  ArrowElbowUpLeft as ArrowElbowUpLeftIcon,
  ArrowElbowUpRight as ArrowElbowUpRightIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowSquareOut as ArrowSquareOutIcon,
  ArrowUp as ArrowUpIcon,
  Bag as BagIcon,
  Balloon as BalloonIcon,
  Bank as BankIcon,
  BatteryCharging as BatteryChargingIcon,
  Bell as BellIcon,
  Bicycle as BicycleIcon,
  Binoculars as BinocularsIcon,
  Bookmark as BookmarkIcon,
  Book as BookIcon,
  Books as BooksIcon,
  Briefcase as BriefcaseIcon,
  Browser as BrowserIcon,
  Buildings as BuildingsIcon,
  Calendar as CalendarIcon,
  Camera as CameraIcon,
  CaretDown as CaretDownIcon,
  CaretLeft as CaretLeftIcon,
  CaretRight as CaretRightIcon,
  CaretUp as CaretUpIcon,
  Car as CarIcon,
  Certificate as CertificateIcon,
  ChartBar as ChartBarIcon,
  ChartLineUp as ChartLineUpIcon,
  ChartPieSlice as ChartPieSliceIcon,
  ChatCircle as ChatCircleIcon,
  ChatCircleText as ChatCircleTextIcon,
  ClipboardText as ClipboardTextIcon,
  Clock as ClockIcon,
  CloudArrowDown as CloudArrowDownIcon,
  CloudArrowUp as CloudArrowUpIcon,
  Cloud as CloudIcon,
  Compass as CompassIcon,
  CreditCard as CreditCardIcon,
  Crown as CrownIcon,
  CurrencyCircleDollar as CurrencyCircleDollarIcon,
  Desktop as DesktopIcon,
  DeviceMobile as DeviceMobileIcon,
  DiceFive as DiceFiveIcon,
  DoorOpen as DoorOpenIcon,
  DownloadSimple as DownloadSimpleIcon,
  Envelope as EnvelopeIcon,
  Eye as EyeIcon,
  Factory as FactoryIcon,
  File as FileIcon,
  Fire as FireIcon,
  Flag as FlagIcon,
  Flower as FlowerIcon,
  Folder as FolderIcon,
  GameController as GameControllerIcon,
  Gear as GearIcon,
  Gift as GiftIcon,
  GitBranch as GitBranchIcon,
  GlobeHemisphereWest as GlobeHemisphereWestIcon,
  Globe as GlobeIcon,
  HandCoins as HandCoinsIcon,
  HandPalm as HandPalmIcon,
  HandWaving as HandWavingIcon,
  HardDrives as HardDrivesIcon,
  Headphones as HeadphonesIcon,
  Heart as HeartIcon,
  House as HouseIcon,
  IdentificationCard as IdentificationCardIcon,
  Image as ImageIcon,
  Key as KeyIcon,
  Lamp as LampIcon,
  Laptop as LaptopIcon,
  Lifebuoy as LifebuoyIcon,
  Lightning as LightningIcon,
  ListBullets as ListBulletsIcon,
  Lock as LockIcon,
  MagnifyingGlass as MagnifyingGlassIcon,
  MapPin as MapPinIcon,
  MapTrifold as MapTrifoldIcon,
  Medal as MedalIcon,
  Megaphone as MegaphoneIcon,
  Microphone as MicrophoneIcon,
  Moon as MoonIcon,
  MusicNotes as MusicNotesIcon,
  Newspaper as NewspaperIcon,
  Package as PackageIcon,
  Palette as PaletteIcon,
  PaperPlaneTilt as PaperPlaneTiltIcon,
  Paperclip as PaperclipIcon,
  Pause as PauseIcon,
  PencilSimple as PencilSimpleIcon,
  Phone as PhoneIcon,
  Play as PlayIcon,
  Receipt as ReceiptIcon,
  Repeat as RepeatIcon,
  RocketLaunch as RocketLaunchIcon,
  Rss as RssIcon,
  Scales as ScalesIcon,
  ShieldCheck as ShieldCheckIcon,
  ShoppingBag as ShoppingBagIcon,
  ShoppingCart as ShoppingCartIcon,
  Shuffle as ShuffleIcon,
  Smiley as SmileyIcon,
  Sparkle as SparkleIcon,
  Star as StarIcon,
  Suitcase as SuitcaseIcon,
  Sun as SunIcon,
  Tag as TagIcon,
  Television as TelevisionIcon,
  ThumbsDown as ThumbsDownIcon,
  ThumbsUp as ThumbsUpIcon,
  Ticket as TicketIcon,
  Train as TrainIcon,
  Tray as TrayIcon,
  UserCircle as UserCircleIcon,
  User as UserIcon,
  UsersThree as UsersThreeIcon,
  VideoCamera as VideoCameraIcon,
  Waveform as WaveformIcon,
} from "@phosphor-icons/react";
import type { ComponentType } from "react";

export type ButtonIconComponent = ComponentType<IconProps>;

function withDuotone(Icon: ButtonIconComponent): ButtonIconComponent {
  function DuotoneButtonIcon(props: IconProps) {
    return <Icon weight="duotone" {...props} />;
  }
  DuotoneButtonIcon.displayName = `Duotone${Icon.displayName ?? Icon.name ?? "ButtonIcon"}`;
  return DuotoneButtonIcon;
}

export const BUTTON_ICON_COMPONENTS = {
  "address-book": withDuotone(AddressBookIcon),
  airplane: withDuotone(AirplaneIcon),
  alarm: withDuotone(AlarmIcon),
  "archive-box": withDuotone(ArchiveBoxIcon),
  armchair: withDuotone(ArmchairIcon),
  "arrow-bend-down-left": withDuotone(ArrowBendDownLeftIcon),
  "arrow-bend-down-right": withDuotone(ArrowBendDownRightIcon),
  "arrow-bend-up-left": withDuotone(ArrowBendUpLeftIcon),
  "arrow-bend-up-right": withDuotone(ArrowBendUpRightIcon),
  "arrow-circle-down": withDuotone(ArrowCircleDownIcon),
  "arrow-circle-left": withDuotone(ArrowCircleLeftIcon),
  "arrow-circle-right": withDuotone(ArrowCircleRightIcon),
  "arrow-circle-up": withDuotone(ArrowCircleUpIcon),
  "arrow-clockwise": withDuotone(ArrowClockwiseIcon),
  "arrow-counter-clockwise": withDuotone(ArrowCounterClockwiseIcon),
  "arrow-down": withDuotone(ArrowDownIcon),
  "arrow-elbow-down-left": withDuotone(ArrowElbowDownLeftIcon),
  "arrow-elbow-down-right": withDuotone(ArrowElbowDownRightIcon),
  "arrow-elbow-left": withDuotone(ArrowElbowLeftIcon),
  "arrow-elbow-right": withDuotone(ArrowElbowRightIcon),
  "arrow-elbow-up-left": withDuotone(ArrowElbowUpLeftIcon),
  "arrow-elbow-up-right": withDuotone(ArrowElbowUpRightIcon),
  "arrow-left": withDuotone(ArrowLeftIcon),
  "arrow-right": withDuotone(ArrowRightIcon),
  "arrow-square-out": withDuotone(ArrowSquareOutIcon),
  "arrow-up": withDuotone(ArrowUpIcon),
  bag: withDuotone(BagIcon),
  balloon: withDuotone(BalloonIcon),
  bank: withDuotone(BankIcon),
  "battery-charging": withDuotone(BatteryChargingIcon),
  bell: withDuotone(BellIcon),
  bicycle: withDuotone(BicycleIcon),
  binoculars: withDuotone(BinocularsIcon),
  bookmark: withDuotone(BookmarkIcon),
  book: withDuotone(BookIcon),
  books: withDuotone(BooksIcon),
  briefcase: withDuotone(BriefcaseIcon),
  browser: withDuotone(BrowserIcon),
  buildings: withDuotone(BuildingsIcon),
  calendar: withDuotone(CalendarIcon),
  camera: withDuotone(CameraIcon),
  "caret-down": withDuotone(CaretDownIcon),
  "caret-left": withDuotone(CaretLeftIcon),
  "caret-right": withDuotone(CaretRightIcon),
  "caret-up": withDuotone(CaretUpIcon),
  car: withDuotone(CarIcon),
  certificate: withDuotone(CertificateIcon),
  "chart-bar": withDuotone(ChartBarIcon),
  "chart-line-up": withDuotone(ChartLineUpIcon),
  "chart-pie-slice": withDuotone(ChartPieSliceIcon),
  "chat-circle": withDuotone(ChatCircleIcon),
  "chat-circle-text": withDuotone(ChatCircleTextIcon),
  "clipboard-text": withDuotone(ClipboardTextIcon),
  clock: withDuotone(ClockIcon),
  cloud: withDuotone(CloudIcon),
  "cloud-arrow-down": withDuotone(CloudArrowDownIcon),
  "cloud-arrow-up": withDuotone(CloudArrowUpIcon),
  compass: withDuotone(CompassIcon),
  "credit-card": withDuotone(CreditCardIcon),
  crown: withDuotone(CrownIcon),
  "currency-circle-dollar": withDuotone(CurrencyCircleDollarIcon),
  desktop: withDuotone(DesktopIcon),
  "device-mobile": withDuotone(DeviceMobileIcon),
  "dice-five": withDuotone(DiceFiveIcon),
  "door-open": withDuotone(DoorOpenIcon),
  "download-simple": withDuotone(DownloadSimpleIcon),
  envelope: withDuotone(EnvelopeIcon),
  eye: withDuotone(EyeIcon),
  factory: withDuotone(FactoryIcon),
  file: withDuotone(FileIcon),
  fire: withDuotone(FireIcon),
  flag: withDuotone(FlagIcon),
  flower: withDuotone(FlowerIcon),
  folder: withDuotone(FolderIcon),
  "game-controller": withDuotone(GameControllerIcon),
  gear: withDuotone(GearIcon),
  gift: withDuotone(GiftIcon),
  "git-branch": withDuotone(GitBranchIcon),
  globe: withDuotone(GlobeIcon),
  "globe-hemisphere-west": withDuotone(GlobeHemisphereWestIcon),
  "hand-coins": withDuotone(HandCoinsIcon),
  "hand-palm": withDuotone(HandPalmIcon),
  "hand-waving": withDuotone(HandWavingIcon),
  "hard-drives": withDuotone(HardDrivesIcon),
  headphones: withDuotone(HeadphonesIcon),
  heart: withDuotone(HeartIcon),
  house: withDuotone(HouseIcon),
  "identification-card": withDuotone(IdentificationCardIcon),
  image: withDuotone(ImageIcon),
  key: withDuotone(KeyIcon),
  lamp: withDuotone(LampIcon),
  laptop: withDuotone(LaptopIcon),
  lifebuoy: withDuotone(LifebuoyIcon),
  lightning: withDuotone(LightningIcon),
  "list-bullets": withDuotone(ListBulletsIcon),
  lock: withDuotone(LockIcon),
  "magnifying-glass": withDuotone(MagnifyingGlassIcon),
  "map-pin": withDuotone(MapPinIcon),
  "map-trifold": withDuotone(MapTrifoldIcon),
  medal: withDuotone(MedalIcon),
  megaphone: withDuotone(MegaphoneIcon),
  microphone: withDuotone(MicrophoneIcon),
  moon: withDuotone(MoonIcon),
  "music-notes": withDuotone(MusicNotesIcon),
  newspaper: withDuotone(NewspaperIcon),
  package: withDuotone(PackageIcon),
  palette: withDuotone(PaletteIcon),
  paperclip: withDuotone(PaperclipIcon),
  "paper-plane-tilt": withDuotone(PaperPlaneTiltIcon),
  pause: withDuotone(PauseIcon),
  "pencil-simple": withDuotone(PencilSimpleIcon),
  phone: withDuotone(PhoneIcon),
  play: withDuotone(PlayIcon),
  receipt: withDuotone(ReceiptIcon),
  repeat: withDuotone(RepeatIcon),
  "rocket-launch": withDuotone(RocketLaunchIcon),
  rss: withDuotone(RssIcon),
  scales: withDuotone(ScalesIcon),
  "shield-check": withDuotone(ShieldCheckIcon),
  "shopping-bag": withDuotone(ShoppingBagIcon),
  "shopping-cart": withDuotone(ShoppingCartIcon),
  shuffle: withDuotone(ShuffleIcon),
  smiley: withDuotone(SmileyIcon),
  sparkle: withDuotone(SparkleIcon),
  star: withDuotone(StarIcon),
  suitcase: withDuotone(SuitcaseIcon),
  sun: withDuotone(SunIcon),
  tag: withDuotone(TagIcon),
  television: withDuotone(TelevisionIcon),
  "thumbs-down": withDuotone(ThumbsDownIcon),
  "thumbs-up": withDuotone(ThumbsUpIcon),
  ticket: withDuotone(TicketIcon),
  train: withDuotone(TrainIcon),
  tray: withDuotone(TrayIcon),
  "user-circle": withDuotone(UserCircleIcon),
  user: withDuotone(UserIcon),
  "users-three": withDuotone(UsersThreeIcon),
  "video-camera": withDuotone(VideoCameraIcon),
  waveform: withDuotone(WaveformIcon),
} as const satisfies Record<string, ButtonIconComponent>;

export type ButtonIconName = keyof typeof BUTTON_ICON_COMPONENTS;

export interface ButtonIconEntry {
  name: ButtonIconName;
  label: string;
  keywords?: readonly string[];
}

export const BUTTON_ICON_LIST: readonly ButtonIconEntry[] = [
  { name: "address-book", label: "Address Book", keywords: ["contacts", "directory"] },
  { name: "airplane", label: "Airplane", keywords: ["flight", "travel"] },
  { name: "alarm", label: "Alarm", keywords: ["clock", "alert"] },
  { name: "archive-box", label: "Archive Box", keywords: ["archive", "storage"] },
  { name: "armchair", label: "Armchair", keywords: ["furniture", "comfort"] },
  { name: "arrow-left", label: "Arrow Left", keywords: ["left"] },
  { name: "arrow-right", label: "Arrow Right", keywords: ["right"] },
  { name: "arrow-up", label: "Arrow Up", keywords: ["up"] },
  { name: "arrow-down", label: "Arrow Down", keywords: ["down"] },
  { name: "arrow-square-out", label: "Arrow Square Out", keywords: ["external", "open"] },
  { name: "bag", label: "Bag", keywords: ["shopping", "store"] },
  { name: "balloon", label: "Balloon", keywords: ["party", "celebration"] },
  { name: "bank", label: "Bank", keywords: ["finance", "building"] },
  { name: "bell", label: "Bell", keywords: ["notification", "alert"] },
  { name: "book", label: "Book", keywords: ["read"] },
  { name: "books", label: "Books", keywords: ["library", "read"] },
  { name: "bookmark", label: "Bookmark", keywords: ["save"] },
  { name: "briefcase", label: "Briefcase", keywords: ["business", "work"] },
  { name: "browser", label: "Browser", keywords: ["web", "window"] },
  { name: "buildings", label: "Buildings", keywords: ["city", "company"] },
  { name: "calendar", label: "Calendar", keywords: ["date", "schedule"] },
  { name: "camera", label: "Camera", keywords: ["photo"] },
  { name: "car", label: "Car", keywords: ["vehicle", "travel"] },
  { name: "certificate", label: "Certificate", keywords: ["award", "badge"] },
  { name: "chart-bar", label: "Chart Bar", keywords: ["analytics", "stats"] },
  { name: "chart-line-up", label: "Chart Line Up", keywords: ["analytics", "growth"] },
  { name: "chat-circle", label: "Chat Circle", keywords: ["message", "bubble"] },
  { name: "clock", label: "Clock", keywords: ["time"] },
  { name: "cloud", label: "Cloud", keywords: ["weather", "online"] },
  { name: "compass", label: "Compass", keywords: ["navigation", "direction"] },
  { name: "credit-card", label: "Credit Card", keywords: ["payment"] },
  { name: "crown", label: "Crown", keywords: ["premium", "royal"] },
  { name: "desktop", label: "Desktop", keywords: ["computer", "screen"] },
  { name: "envelope", label: "Envelope", keywords: ["mail", "email"] },
  { name: "eye", label: "Eye", keywords: ["view", "show"] },
  { name: "file", label: "File", keywords: ["document"] },
  { name: "fire", label: "Fire", keywords: ["hot", "flame"] },
  { name: "flag", label: "Flag", keywords: ["marker", "goal"] },
  { name: "flower", label: "Flower", keywords: ["nature", "garden"] },
  { name: "folder", label: "Folder", keywords: ["directory"] },
  { name: "gear", label: "Gear", keywords: ["settings"] },
  { name: "gift", label: "Gift", keywords: ["present"] },
  { name: "globe", label: "Globe", keywords: ["world", "website"] },
  { name: "headphones", label: "Headphones", keywords: ["audio", "music"] },
  { name: "heart", label: "Heart", keywords: ["favorite", "like"] },
  { name: "house", label: "House", keywords: ["home"] },
  { name: "image", label: "Image", keywords: ["picture", "photo"] },
  { name: "key", label: "Key", keywords: ["access"] },
  { name: "lightning", label: "Lightning", keywords: ["fast", "energy"] },
  { name: "lock", label: "Lock", keywords: ["secure", "privacy"] },
  { name: "magnifying-glass", label: "Magnifying Glass", keywords: ["search"] },
  { name: "map-pin", label: "Map Pin", keywords: ["location", "pin"] },
  { name: "medal", label: "Medal", keywords: ["award", "winner"] },
  { name: "megaphone", label: "Megaphone", keywords: ["announcement", "marketing"] },
  { name: "microphone", label: "Microphone", keywords: ["audio", "voice"] },
  { name: "moon", label: "Moon", keywords: ["night", "theme"] },
  { name: "music-notes", label: "Music Notes", keywords: ["music", "audio"] },
  { name: "newspaper", label: "Newspaper", keywords: ["news", "article"] },
  { name: "package", label: "Package", keywords: ["box", "delivery"] },
  { name: "palette", label: "Palette", keywords: ["design", "color"] },
  { name: "paper-plane-tilt", label: "Paper Plane", keywords: ["send"] },
  { name: "pencil-simple", label: "Pencil Simple", keywords: ["edit", "write"] },
  { name: "phone", label: "Phone", keywords: ["call", "telephone"] },
  { name: "play", label: "Play", keywords: ["start"] },
  { name: "rocket-launch", label: "Rocket Launch", keywords: ["launch", "fast"] },
  { name: "shield-check", label: "Shield Check", keywords: ["security", "safe"] },
  { name: "shopping-cart", label: "Shopping Cart", keywords: ["cart", "shop"] },
  { name: "sparkle", label: "Sparkle", keywords: ["magic", "highlight"] },
  { name: "star", label: "Star", keywords: ["favorite", "featured"] },
  { name: "sun", label: "Sun", keywords: ["day", "weather"] },
  { name: "tag", label: "Tag", keywords: ["label", "price"] },
  { name: "thumbs-up", label: "Thumbs Up", keywords: ["like"] },
  { name: "thumbs-down", label: "Thumbs Down", keywords: ["dislike"] },
  { name: "user", label: "User", keywords: ["person"] },
  { name: "users-three", label: "Users", keywords: ["group", "people"] },
  { name: "video-camera", label: "Video Camera", keywords: ["video"] },
  { name: "waveform", label: "Waveform", keywords: ["audio", "sound"] },
];

export function getButtonIconComponent(name: string | null | undefined): ButtonIconComponent | null {
  if (!name || !(name in BUTTON_ICON_COMPONENTS)) {
    return null;
  }
  return BUTTON_ICON_COMPONENTS[name as ButtonIconName];
}
