/**
 * Repository contract for the external developer-account system that backs
 * developer.musiccloud.io (MC-064). Kept deliberately separate from
 * {@link AdminRepository}: developer accounts are self-service portal users,
 * not dashboard administrators, and share no tables, auth flow or lifecycle
 * with `admin_users`.
 *
 * The contract covers the email/password auth flow — account creation,
 * email verification, login bookkeeping and password reset — plus the
 * supporting identity and single-use email-token tables. GitHub OAuth lands
 * in a follow-up (MC-065) and reuses {@link createDeveloperIdentity} /
 * {@link findDeveloperIdentity}.
 *
 * Implementations translate these calls into persistent rows without
 * exposing SQL to the route/service layer.
 */

/**
 * Developer-account DTO returned by the repository. Timestamp columns are
 * surfaced as epoch milliseconds (matching the {@link AdminUser} contract)
 * rather than `Date`, and `0` for an absent required timestamp.
 *
 * @property id - Stable account id (text PK, nanoid-generated).
 * @property email - Unique login email, stored verbatim.
 * @property emailVerifiedAt - Epoch ms when the verification token was
 *   consumed, or `null` while the account is still unverified. Login is
 *   gated on this being non-null.
 * @property passwordHash - bcrypt hash, or `null` for a pure-OAuth account
 *   that has never set a password (reserved for MC-065).
 * @property displayName - Optional display name shown in the portal.
 * @property avatarUrl - Optional avatar URL.
 * @property plan - Billing plan; currently always `"free"`.
 * @property status - `"active"` or `"suspended"`.
 * @property createdAt - Account creation time, epoch ms.
 * @property updatedAt - Last mutation time, epoch ms.
 * @property lastLoginAt - Last successful login, epoch ms, or `null` if the
 *   account has never logged in.
 */
export interface DeveloperAccount {
  id: string;
  email: string;
  emailVerifiedAt: number | null;
  passwordHash: string | null;
  displayName: string | null;
  avatarUrl: string | null;
  plan: string;
  status: string;
  createdAt: number;
  updatedAt: number;
  lastLoginAt: number | null;
}

/**
 * Authentication-identity DTO linking a {@link DeveloperAccount} to a
 * provider. `provider = "email"` carries a `null` `providerUserId`;
 * `provider = "github"` carries the external GitHub user id.
 *
 * @property id - Stable identity id (text PK, nanoid-generated).
 * @property accountId - Owning developer account id.
 * @property provider - `"email"` or `"github"`.
 * @property providerUserId - External provider user id, or `null` for the
 *   built-in email provider.
 * @property createdAt - Identity creation time, epoch ms.
 */
export interface DeveloperIdentity {
  id: string;
  accountId: string;
  provider: string;
  providerUserId: string | null;
  createdAt: number;
}

/**
 * Single-use email-token DTO for account verification and password reset.
 * Only the SHA-256 hash of the raw token is persisted; the raw token lives
 * exclusively in the emailed link.
 *
 * @property id - Stable token id (text PK, nanoid-generated).
 * @property accountId - Owning developer account id.
 * @property purpose - `"verify"` or `"reset"`.
 * @property tokenHash - Hex-encoded SHA-256 of the raw token.
 * @property expiresAt - Expiry time, epoch ms; the token is invalid once
 *   `Date.now()` passes this value.
 * @property consumedAt - Epoch ms when the token was consumed, or `null`
 *   while it is still claimable. A consumed token cannot be replayed.
 * @property createdAt - Token creation time, epoch ms.
 */
export interface DeveloperEmailToken {
  id: string;
  accountId: string;
  purpose: string;
  tokenHash: string;
  expiresAt: number;
  consumedAt: number | null;
  createdAt: number;
}

/**
 * Persistence contract for developer accounts, their auth identities and
 * single-use email tokens. See the file-level comment for scope.
 */
export interface DeveloperRepository {
  /**
   * Creates a new (unverified) developer account.
   *
   * The id is generated by the implementation. `emailVerifiedAt` and
   * `lastLoginAt` start `null`; `plan` defaults to `"free"` and `status` to
   * `"active"`.
   *
   * @param data - Account payload. `passwordHash` is omitted for accounts
   *   created via OAuth; `displayName` and `avatarUrl` are optional profile
   *   fields.
   * @returns The freshly created account DTO.
   */
  createDeveloperAccount(data: {
    email: string;
    passwordHash?: string | null;
    displayName?: string | null;
    avatarUrl?: string | null;
  }): Promise<DeveloperAccount>;

  /**
   * Looks up a developer account by primary key.
   *
   * @param id - The account id.
   * @returns The matching account, or `null` when no row matches.
   */
  findDeveloperAccountById(id: string): Promise<DeveloperAccount | null>;

  /**
   * Looks up a developer account by email.
   *
   * @param email - Login email; matched with `=` (case-sensitive).
   * @returns The matching account, or `null` when no row matches.
   */
  findDeveloperAccountByEmail(email: string): Promise<DeveloperAccount | null>;

  /**
   * Lists all developer accounts ordered by creation time (newest first).
   * Includes the count of active API clients each account owns for the
   * dashboard overview.
   *
   * @returns Array of account DTOs, each extended with `clientCount`.
   */
  listDeveloperAccounts(): Promise<(DeveloperAccount & { clientCount: number })[]>;

  /**
   * Stamps `email_verified_at = NOW()` (and bumps `updated_at`) on the
   * given account, marking its email as verified.
   *
   * @param id - The account id.
   * @returns The updated account, or `null` when no row matches.
   */
  markDeveloperEmailVerified(id: string): Promise<DeveloperAccount | null>;

  /**
   * Stamps `last_login_at = NOW()` (and bumps `updated_at`) on the given
   * account.
   *
   * @param id - The account id.
   * @returns A promise that resolves when the update completes.
   */
  updateDeveloperLastLogin(id: string): Promise<void>;

  /**
   * Sets the account's password hash and bumps `updated_at`. Used by the
   * password-reset flow.
   *
   * @param id - The account id.
   * @param passwordHash - The new bcrypt hash.
   * @returns The updated account, or `null` when no row matches.
   */
  setDeveloperPassword(id: string, passwordHash: string): Promise<DeveloperAccount | null>;

  /**
   * Permanently deletes a developer account. All owned rows in
   * `developer_identities`, `developer_email_tokens`, `api_access_requests`
   * and `api_clients` (and, transitively, their tokens and audit events)
   * cascade-delete via `ON DELETE CASCADE`, so this single call is sufficient
   * to remove the account's entire footprint.
   *
   * @param id - The account id.
   * @returns `true` if a row was deleted, `false` if no account matched `id`.
   */
  deleteDeveloperAccount(id: string): Promise<boolean>;

  /**
   * Clears the account's password by setting `password_hash = NULL` and bumps
   * `updated_at`. Invoked when GitHub OAuth links to an account that is still
   * unverified: GitHub now proves mailbox ownership, so any password that was
   * set on the unverified account has no trust value and is discarded to
   * prevent an account-takeover via a pre-seeded password.
   *
   * @param id - The account id.
   * @returns A promise that resolves when the update completes.
   */
  clearDeveloperPassword(id: string): Promise<void>;

  /**
   * Creates an authentication identity for an account. The id is generated
   * by the implementation.
   *
   * @param data - Identity payload. `providerUserId` is `null`/omitted for
   *   the built-in email provider.
   * @returns The freshly created identity DTO.
   */
  createDeveloperIdentity(data: {
    accountId: string;
    provider: string;
    providerUserId?: string | null;
  }): Promise<DeveloperIdentity>;

  /**
   * Looks up an identity by `(provider, providerUserId)` — the lookup used
   * during OAuth sign-in to find the linked account.
   *
   * @param provider - `"email"` or `"github"`.
   * @param providerUserId - External provider user id.
   * @returns The matching identity, or `null` when no row matches.
   */
  findDeveloperIdentity(provider: string, providerUserId: string): Promise<DeveloperIdentity | null>;
  /**
   * Lists every auth identity linked to an account (email, GitHub, …) — part
   * of the GDPR export package (MC-085).
   *
   * @param accountId - The developer account's id.
   * @returns The account's identities, oldest first.
   */
  listDeveloperIdentitiesByAccount(accountId: string): Promise<DeveloperIdentity[]>;

  /**
   * Creates a single-use email token. The raw token is hashed by the caller;
   * only the hash is stored. The id is generated by the implementation.
   *
   * @param data - Token payload. `expiresAt` is a `Date`; the row's
   *   `consumed_at` starts `null`.
   * @returns The freshly created token DTO.
   */
  createDeveloperEmailToken(data: {
    accountId: string;
    purpose: string;
    tokenHash: string;
    expiresAt: Date;
  }): Promise<DeveloperEmailToken>;

  /**
   * Finds a still-claimable email token: matching `(tokenHash, purpose)`,
   * not yet consumed and not yet expired.
   *
   * @param tokenHash - Hex-encoded SHA-256 of the raw token.
   * @param purpose - `"verify"` or `"reset"`.
   * @returns The matching token, or `null` if none is claimable.
   */
  findActiveDeveloperEmailToken(tokenHash: string, purpose: string): Promise<DeveloperEmailToken | null>;

  /**
   * Marks a token consumed by stamping `consumed_at = NOW()`. Re-checks
   * `consumed_at IS NULL` in the WHERE clause so a concurrent consume of the
   * same token returns `false` instead of double-spending it.
   *
   * @param id - The token id.
   * @returns `true` if the token was consumed by this call, `false` if it
   *   was already consumed or does not exist.
   */
  consumeDeveloperEmailToken(id: string): Promise<boolean>;
}
