export const artistCopy = {
  popularTracks: "Popular Tracks",
  upcomingEvents: "Upcoming Events",
  fanCount: "Fans",
  lastfmPlays: "Last.fm Plays",
  similar: "Similar artists",
  closeInfo: "Close artist info",
  infoTitle: "Artist Info",
  mobileButton: "Artist Info",
  similarArtists: "Similar Artists",
  similarTracks: "Similar Tracks",
  eventsProvidedBy: "Event data provided by Bandsintown & Ticketmaster",
  profileProvidedBy: "Artist data provided by Spotify, Deezer & Last.fm",
  profileProvidedByJamendo: "Artist data provided by Jamendo",
  empty: "No artist details available.",
  error: "Artist data could not be loaded.",
  statusLoading: "ARTIST DATA LOADING...",
  statusReady: "ARTIST DATA READY",
  statusEmpty: "ARTIST DATA EMPTY",
  statusError: (code: string) => `ARTIST DATA ERROR ${code}`,
  statusResolveError: "RESOLVE ERROR",
} as const;
