export const creativeCommonsCopy = {
  sectionTitle: "Creative Commons",
  licenseUnknown: "Creative Commons",
  download: "Download track",
  openOnJamendo: "Open on Jamendo",
  opensInNewWindow: "opens in new window",
  details: {
    title: "Details",
    genres: "Genres",
    instruments: "Instruments",
    mood: "Mood",
    vocals: "Vocal/Instrumental",
    voice: "Voice",
    tempo: "Tempo",
    character: "Character",
    language: "Language",
  },
  stats: {
    listens: "Listens",
    downloads: "Downloads",
    favorited: "Favorites",
    playlisted: "Playlisted",
    rating: "Rating",
  },
  downloadFormat: "Download format",
  buyBandcamp: "Buy on Bandcamp",
} as const;
