export const discoveryCopy = {
  disambiguation: {
    title: "Did you mean?",
    subtitle: "We found multiple matches. Pick the right one.",
    cancel: "None of these? Try a different search.",
    loading: "Loading selected track...",
    found: (count: number) => `Found ${count} possible matches. Please select the correct one.`,
    resolving: {
      title: "Resolving",
      subtitle: "We're fetching the streaming links for your selection.",
    },
  },
  genreSearch: {
    subtitle: "Pick a result to see it across every streaming service.",
    resolveTrack: (title: string, artists: string) => `Resolve track "${title}" by ${artists}`,
    resolveAlbum: (title: string, artists: string) => `Resolve album "${title}" by ${artists}`,
    resolveArtist: (name: string) => `Resolve artist ${name}`,
    empty: "No results for this genre.",
    tracks: (count: number) => `Tracks (${count})`,
    albums: (count: number) => `Albums (${count})`,
    artists: (count: number) => `Artists (${count})`,
    cancel: "Start a new search",
    loading: "Loading selected result...",
    backToResults: "Back to discovery results",
    backToBrowse: "All genres",
    summary: {
      hot: (counts: string, genres: string) => `${counts} in ${genres}`,
      mixed: (counts: string, genres: string) => `${counts} in ${genres} — a mixed selection`,
      allTypes: "tracks, albums and artists",
      track: "track",
      tracks: "tracks",
      album: "album",
      albums: "albums",
      artist: "artist",
      artists: "artists",
      and: "and",
      or: "or",
    },
  },
  genreBrowse: {
    title: "Explore Genres",
    subtitle: "Pick a genre to discover tracks, albums, and artists",
    search: (displayName: string) => `Search ${displayName}`,
  },
} as const;
