/**
 * @file Curated list of Iconsax icon names selectable for an API tier (MC-105).
 *
 * Single source of truth shared across the stack: the admin dashboard's tier
 * icon picker offers exactly these, the backend validates a tier's `icon`
 * against this list, and the Developer Portal renders only these on its
 * pricing cards. Every name is a component exported by the free `iconsax-react`
 * set (verified against its type definitions); the apps import the matching
 * component by name and render it in the Bulk variant.
 *
 * 256 icons, grouped by theme purely for readability. The order also drives the
 * picker's grid order. Crypto coins, brand logos and zodiac signs are
 * deliberately excluded.
 */

/**
 * The selectable tier icon names. `as const` so {@link TierIconName} is a
 * precise union and the list can be used for runtime validation.
 */
export const TIER_ICONS = [
  // Rank & reward
  "Medal",
  "MedalStar",
  "Cup",
  "Crown",
  "Crown1",
  "Award",
  "Star",
  "Star1",
  "Ranking",
  "Rank",
  "Gift",
  "Coin",
  "Coin1",
  // Music & audio
  "Music",
  "MusicCircle",
  "MusicSquare",
  "MusicDashboard",
  "MusicPlay",
  "MusicFilter",
  "MusicLibrary2",
  "MusicPlaylist",
  "Musicnote",
  "MiniMusicSqaure",
  "Microphone",
  "Microphone2",
  "Radio",
  // Building & venue
  "Building",
  "Building3",
  "Building4",
  "Buildings",
  "Buildings2",
  "House",
  "House2",
  "Home",
  "Home2",
  "Courthouse",
  "Bank",
  "Shop",
  "Hospital",
  // Abstract & category
  "Category",
  "Category2",
  "Element",
  "Element2",
  "Element3",
  "Element4",
  "Hierarchy",
  "Hierarchy2",
  "HierarchySquare",
  "Box",
  "Box1",
  "Box2",
  "Layer",
  // Business & analytics
  "Briefcase",
  "Chart",
  "Chart1",
  "Chart2",
  "ChartSquare",
  "Activity",
  "PresentionChart",
  "Graph",
  "Diagram",
  "TrendUp",
  "TrendDown",
  "Status",
  "StatusUp",
  // Finance
  "Wallet",
  "Wallet1",
  "Wallet2",
  "Wallet3",
  "EmptyWallet",
  "Card",
  "Cards",
  "Money",
  "Moneys",
  "MoneyRecive",
  "MoneySend",
  "MoneyChange",
  "DollarCircle",
  // Energy & flash
  "Flash",
  "FlashCircle",
  "Flashy",
  "Lamp",
  "LampOn",
  "LampCharge",
  "Electricity",
  // Tech & devices
  "Code",
  "CodeCircle",
  "Cpu",
  "CpuCharge",
  "DocumentCode",
  "Devices",
  "Mobile",
  "Monitor",
  "MonitorMobbile",
  "Keyboard",
  "Mouse",
  "Printer",
  "Ram",
  // Cloud & global
  "Cloud",
  "CloudConnection",
  "CloudSunny",
  "CloudLightning",
  "Global",
  "GlobalSearch",
  "Wifi",
  "Send",
  "Send2",
  // Nature & element
  "Cd",
  "Sun",
  "Sun1",
  "Moon",
  "Tree",
  "Wind",
  "Drop",
  // Security
  "Shield",
  "ShieldTick",
  "ShieldSecurity",
  "SecurityUser",
  "Security",
  "SecurityCard",
  "SecuritySafe",
  "Lock",
  "Lock1",
  "Unlock",
  "Key",
  "KeySquare",
  "PasswordCheck",
  // People
  "Profile",
  "Profile2User",
  "ProfileCircle",
  "ProfileAdd",
  "ProfileTick",
  "People",
  "User",
  "UserSquare",
  "UserTick",
  "Man",
  "Woman",
  "Personalcard",
  "TagUser",
  // Communication
  "Message",
  "Messages",
  "MessageText",
  "MessageQuestion",
  "MessageFavorite",
  "Sms",
  "SmsNotification",
  "Notification",
  "NotificationBing",
  "Call",
  "CallCalling",
  "Direct",
  "DirectInbox",
  // Documents & notes
  "Document",
  "DocumentText",
  "DocumentCopy",
  "DocumentDownload",
  "DocumentUpload",
  "DocumentCloud",
  "Folder",
  "FolderOpen",
  "FolderCloud",
  "Note",
  "Note1",
  "NoteText",
  "Book",
  // Media & photo
  "Camera",
  "Gallery",
  "Image",
  "Video",
  "VideoPlay",
  "VideoCircle",
  "Play",
  "PlayCircle",
  "Pause",
  "Stop",
  "Record",
  "Story",
  "Mask",
  // Shopping
  "Bag",
  "Bag2",
  "BagHappy",
  "ShoppingBag",
  "ShoppingCart",
  "ShopAdd",
  "Tag",
  "Tag2",
  "Ticket",
  "Ticket2",
  "TicketStar",
  "TicketDiscount",
  "DiscountShape",
  // Time
  "Clock",
  "Timer",
  "Timer1",
  "TimerStart",
  "Alarm",
  "Calendar",
  "Calendar2",
  "CalendarTick",
  "CalendarAdd",
  "Watch",
  "WristClock",
  "SecurityTime",
  // Tools
  "Setting2",
  "Settings",
  "Filter",
  "FilterSearch",
  "SearchNormal",
  "SearchStatus",
  "Edit",
  "Edit2",
  "Trash",
  "Save2",
  "RotateLeft",
  "RotateRight",
  "Scissor",
  // Transport & location
  "Car",
  "SmartCar",
  "Ship",
  "Bus",
  "Truck",
  "TruckFast",
  "Location",
  "Map",
  "Map1",
  "Gps",
  "Routing",
  "GasStation",
  "Driving",
  // Health & science
  "Health",
  "Lifebuoy",
  "ChemicalGlass",
  "Microscope",
  "Milk",
  "Weight",
  "WeightMeter",
  "Judge",
  "Teacher",
  "Signpost",
  "Glass",
  // Symbols & fun
  "Heart",
  "HeartCircle",
  "Like",
  "Like1",
  "Dislike",
  "EmojiHappy",
  "EmojiNormal",
  "EmojiSad",
  "Happyemoji",
  "Smileys",
  "Lovely",
  "Flag",
  "Flag2",
  // Text & format
  "Text",
  "TextBold",
] as const;

/** A valid tier icon name: one of {@link TIER_ICONS}. */
export type TierIconName = (typeof TIER_ICONS)[number];

/** Runtime guard: whether `value` is a selectable tier icon name. */
export function isTierIconName(value: unknown): value is TierIconName {
  return typeof value === "string" && (TIER_ICONS as readonly string[]).includes(value);
}
