export const dashboardCopy = {
  common: {
    ok: "OK",
    cancel: "Cancel",
    create: "Create",
    save: "Save",
    saving: "Saving\u2026",
    saved: "Saved",
    saveError: "Error saving",
    edit: "Edit",
    delete: "Delete",
    remove: "Remove",
    duplicate: "Duplicate",
    close: "Close",
    loading: "Loading\u2026",
    copied: "Copied!",
    unknownError: "Unknown error",
    alignment: "Alignment",
    alignLeft: "Left",
    alignCenter: "Center",
    alignRight: "Right",
    nameConflict: "Name already taken",
    importExport: {
      exportAction: "Export",
      importAction: "Import",
      importError: "Import failed",
      invalidFile: "Invalid file",
      newNameLabel: "New name",
      overwrite: "Overwrite",
      rename: "Rename",
      skip: "Skip",
    },
  },
  layout: {
    menuOpen: "Open menu",
    menuClose: "Close menu",
    resizeSidebar: "Resize sidebar",
    pageFallbackTitle: "Dashboard",
    pagesSaveBar: {
      saving: "Saving…",
      save: "Save ({count})",
      discard: "Discard",
      error: "1 error",
      errors: "{count} errors",
      discardTitle: "Discard changes?",
      discardDescription: "All unsaved changes will be lost. This action cannot be undone.",
    },
    sidebar: {
      sectionGeneral: "General",
      sectionMusic: "Music",
      sectionContent: "Content",
      sectionTemplates: "Templates",
      sectionSystem: "System",
      overview: "Overview",
      tracks: "Tracks",
      albums: "Albums",
      artists: "Artists",
      users: "Users",
      pages: "Pages",
      pagesOverview: "Overview",
      navigations: "Navigations",
      emailTemplates: "Email Templates",
      emailTemplatesOverview: "Overview",
      emailBranding: "Email branding",
      system: "System",
      sectionDeveloper: "Developer",
      apiAccessRequests: "API Access Requests",
      clientsAndTokens: "API Keys",
      developerAccounts: "Developer Accounts",
      tiers: "Tiers",
      settings: "Settings",
      services: "Services",
      design: "Design",
      actions: "Actions",
      expandAll: "Expand all",
      collapseAll: "Collapse all",
      expandAllAria: "Expand all groups",
      collapseAllAria: "Collapse all groups",
      editProfile: "Edit profile",
      logout: "Log out",
      logoutConfirmTitle: "Log out",
      logoutConfirmDescription: "Are you sure you want to log out?",
      logoutConfirmAction: "Log out",
      logoutSkipConfirm: "Don't ask again",
      logoutConfirmLabel: "Logout confirmation",
    },
  },
  auth: {
    login: {
      title: "Sign In",
      username: "Username",
      password: "Password",
      invalidCredentials: "Invalid username or password",
      submit: "Sign In",
      submitLoading: "Signing in\u2026",
    },
    invite: {
      title: "Accept Invitation",
      subtitle: "Set a password for your account.",
      password: "Password",
      confirmPassword: "Confirm Password",
      passwordMismatch: "Passwords do not match",
      invalidLink: "Invalid or expired invitation link",
      submit: "Activate Account",
      submitLoading: "Activating\u2026",
      toLogin: "Go to Login",
    },
    setup: {
      welcome: "Welcome",
      title: "Initial Setup",
      subtitle: "Create the first administrator account.",
      email: "Email",
      confirmPassword: "Confirm Password",
      passwordMismatch: "Passwords do not match",
      genericError: "An error occurred",
      submit: "Create Account",
      submitLoading: "Creating\u2026",
    },
  },
  dashboard: {
    overviewTitle: "Overview",
    cards: {
      tracks: "Tracks",
      albums: "Albums",
      artists: "Artist Profiles",
      artistEntities: "Artist Entities",
      users: "Users",
      pendingApiAccessRequests: "Pending API Requests",
    },
  },
  developer: {
    requestsTitle: "API Access Requests",
    requestsFilterAll: "All",
    requestsFilterPending: "Pending",
    requestsFilterApproved: "Approved",
    requestsFilterRejected: "Rejected",
    colApp: "App",
    colDeveloper: "Developer",
    colTraffic: "Traffic Est.",
    colSubmitted: "Submitted",
    colStatus: "Status",
    detailBackLabel: "\u2190 API Access Requests",
    detailApprove: "Approve",
    detailReject: "Reject",
    detailRejectReasonLabel: "Reason (required)",
    detailRejectReasonPlaceholder: "Reason for rejection\u2026",
    detailRejectConfirm: "Reject",
    detailRejectCancel: "Cancel",
    detailRateLimitMinute: "Requests / Minute",
    detailRateLimitDay: "Requests / Day",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusActive: "Active",
    statusSuspended: "Suspended",
    statusRevoked: "Revoked",
    clientsTitle: "API Keys",
    clientsEmpty: "No API keys",
    clientsEmptyHint: "Approved API access requests appear here with their key.",
    clientTrafficLabel: "Configured volume",
    clientsTokensLabel: "Tokens",
    clientsNoTokens: "No tokens",
    clientsCreateToken: "Create token",
    clientsRevokeToken: "Revoke",
    clientsRotateToken: "Rotate",
    clientsDeactivateToken: "Deactivate",
    clientsSearchPlaceholder: "Search keys…",
    clientsSearchNoResults: "No results for “{q}”",
    tokenRevealCopy: "Copy to clipboard",
    accountsTitle: "Developer Accounts",
    colEmail: "Email",
    colDisplayName: "Name",
    colTier: "Tier",
    tierNone: "No tier",
    tierInactiveBadge: "No longer active",
    tierDropdownInactiveSuffix: "(inactive)",
    clientCustomBadge: "Custom",
    clientInheritsFrom: "inherits from {tier}",
    colAppName: "App",
    colRegistered: "Registered",
    overviewCardLabel: "Pending API Requests",
    noRequests: "No open requests",
    noRequestsHint: "When developers request API access, they'll appear here for review.",
    requestCount: "{n} requests",
    accountCount: "{n} accounts",
    noAccounts: "No developer accounts",
    noAccountsHint: "Registered developers appear here once they sign up in the Developer Portal.",
    accountDetailTitle: "Developer Account",
    accountDetailBackLabel: "← Developer Accounts",
    accountDetailDeactivate: "Deactivate",
    accountDetailDeactivateHint:
      "Login remains possible, but the API key is blocked. The developer can only request GDPR data or delete their account.",
    accountDetailReactivate: "Reactivate",
    accountDetailDelete: "Delete",
    accountDetailDeleteHint:
      "The account and all associated data (API clients, tokens, requests) will be permanently deleted.",
    accountDetailDeleteConfirm: "Really delete account?",
    copied: "Copied!",
    descriptionLabel: "Description",
    rateLimitsLabel: "Rate Limits",
    perMinute: "/minute",
    perDay: "/day",
    colKey: "API Key",
    tiersTitle: "Tiers",
    tierCreate: "Create Tier",
    tierEdit: "Edit Tier",
    tierDeleteTitle: "Delete Tier",
    tierDeleteConfirm: "Are you sure you want to delete this tier?",
    colName: "Name",
    colDescription: "Description",
    colAttribution: "Attribution",
    colPrice: "Price",
    colPriceMonthly: "Monthly price (€)",
    colPriceYearly: "Yearly price (€)",
    colColor: "Color",
    colIcon: "Icon",
    colButtonLabel: "Button label",
    colButtonLabelPlaceholder: "Default: “I want this”",
    iconPickerSearch: "Search icons…",
    iconNone: "No icon",
    colSortOrder: "Sort Order",
    colActive: "Active",
    colDisableReason: "Disable reason",
    tierDisabledBadge: "Disabled",
    colRecommended: "Recommended",
    tierRecommendedBadge: "Recommended",
    noTiers: "No tiers",
    noTiersHint: "Create your first API tier using the button above.",
    featuresLabel: "Features",
    featureAddButton: "Add feature",
    featureLabelPlaceholder: "e.g. Unlimited requests",
    featureMoveUp: "Move up",
    featureMoveDown: "Move down",
    featureRemove: "Remove",
    featureMaxReached: "Maximum of 12 features allowed.",
    settingsTitle: "Developer Settings",
    availabilityTitle: "Portal availability",
    availabilityDescription: "Control whether the Developer Portal is publicly available.",
    portalPublicLabel: "Developer Portal",
    portalPublicDescription: "Makes the Developer Portal publicly available.",
    maintenanceLabel: "Maintenance",
    maintenanceDescription: "Temporarily closes the portal for maintenance.",
    apiReferenceNotice: "The API reference remains available at all times.",
  },
  music: {
    columns: {
      title: "Title",
      artists: "Artists",
      source: "Source",
      links: "Services",
      added: "Added",
    },
    tracks: {
      title: "Tracks",
      searchPlaceholder: "Search tracks\u2026",
      total: "tracks",
      noTracks: "No tracks yet",
    },
    trackEdit: {
      backLabel: "Tracks",
      title: "Title",
      artists: "Artists",
      artistsHint: "Comma-separated",
      albumName: "Album",
      isrc: "ISRC",
      artworkUrl: "Artwork URL",
      sourceService: "Source",
      sourceUrl: "Source URL",
      serviceLinks: "Service Links",
      serviceUrls: "Service URLs",
      createdAt: "Added",
      notFound: "Track not found",
    },
    albums: {
      title: "Albums",
      searchPlaceholder: "Search albums\u2026",
      total: "albums",
      noAlbums: "No albums yet",
      colTracks: "Tracks",
    },
    artists: {
      title: "Artist Profiles",
      searchPlaceholder: "Search artist profiles\u2026",
      total: "artist profiles",
      noArtists: "No artist profiles yet",
      deleteButton: "Delete profiles ({count})",
      deleteConfirmTitle: "Delete artist profiles",
      deleteConfirmDescription:
        "{count} artist profiles will be removed. Normalized artist entities and track/album credits stay intact.",
      deleteConfirmAction: "Delete profiles",
      colName: "Name",
      colGenres: "Genres",
      refreshLabel: "Refresh",
      refreshTooltip: "Reload artist data from the source",
      refreshConfirm: "Refreshed",
    },
    table: {
      deleteButton: "Delete ({count})",
      deleteConfirmTitle: "Delete entries",
      deleteConfirmDescription: "{count} entries will be permanently deleted.",
    },
  },
  system: {
    title: "System",
    cacheTitle: "Cache",
    artistCacheLabel: "Clear artist cache",
    artistCacheDescription:
      "Deletes all cached artist info (top tracks, profile, tour dates). Will be reloaded on next request.",
    artistCacheClear: "Clear",
    shareCacheLabel: "Refresh share cache",
    shareCacheDescription:
      "Marks every track, album and artist as stale. The next request to a share re-fetches fresh source data from the services. Share URLs remain intact.",
    shareCacheClear: "Refresh",
    shareCacheSuccess: "{tracks} tracks, {albums} albums, {artists} artists refreshed.",
    genreCacheLabel: "Clear genre cache",
    genreCacheDescription:
      "Drops every generated genre artwork from the database and resets the in-memory browse-grid cache. The next `genre:?` request refetches tiles and re-renders the artworks.",
    genreCacheClear: "Clear",
    dangerZoneTitle: "Danger Zone",
    deleteAllLabel: "Delete all data",
    deleteAllDescriptionWithCounts:
      "Deletes {tracks} {tracksLabel} and {albums} {albumsLabel} including all links, short URLs and caches. User accounts remain untouched.",
    deleteAllDescriptionGeneric:
      "Deletes all tracks, albums, links, short URLs and caches. User accounts remain untouched.",
    deleteAllIrreversible: "This action cannot be undone.",
    deleteAllSuccess: "{tracks} {tracksLabel} and {albums} {albumsLabel} deleted.",
    deleteAllButton: "Reset\u2026",
    deleteAllConfirm: "Yes, delete all",
    entriesDeleted: "{count} entries deleted.",
    trackingTitle: "Website Tracking",
    trackingLabel: "Umami Analytics",
    trackingDescription:
      "Enables the Umami tracking script on the website. When disabled, no tracking code is embedded.",
    trackingEnabled: "Active",
    trackingDisabled: "Disabled",
  },
  design: {
    title: "Design",
    description: "Website appearance — glass material, colours and night sky.",
    jsonLabel: "Design token JSON",
    jsonHint: "Paste the settings JSON exported from the prototype here and save.",
    reset: "Discard changes",
    validJson: "Valid JSON",
    invalidJson: "Invalid JSON",
    invalidValues: "{count} values out of range, defaults applied",
    reloadHint: "Changes appear on the site on its next load (up to 60 seconds).",
  },
  services: {
    title: "Services",
    subtitle:
      "Enable or disable resolve plugins. Disabled services are skipped during cross-service matching and their cached links are hidden on share pages.",
    lastServiceWarning: "At least one plugin must be enabled for resolves to work.",
    enabled: "Enabled",
    disabled: "Disabled",
    availableLabel: "Available",
    credentialsMissingLabel: "Credentials missing",
    missingEnvPrefix: "Missing:",
    capabilityTrack: "Track",
    capabilityAlbum: "Album",
    capabilityArtist: "Artist",
    capabilityIsrc: "ISRC",
    capabilityPreview: "Preview",
    capabilityArtwork: "Artwork",
    toggleAction: "Toggle",
    toggleError: "Toggle failed.",
    loadError: "Failed to load the plugin list.",
    empty: "No plugins installed.",
  },
  users: {
    title: "Users",
    inviteUser: "Invite User",
    you: "(you)",
    role: { owner: "Owner", admin: "Administrator", moderator: "Moderator" },
    removeConfirmTitle: "Remove User",
    removeConfirmDescription: "Are you sure you want to remove this user?",
    createCard: {
      title: "Invite User",
      role: "Role",
      username: "Username",
      email: "Email",
      inviteFlowHint: "The user will receive an invitation link.",
      inviteCreated: "Invitation Created",
      inviteHint: "Share the following link with the user:",
      inviteLink: "Invitation Link",
      copyInvite: "Copy Link",
      errorCreating: "Error creating",
      creating: "Creating\u2026",
      create: "Invite",
    },
    editCard: {
      title: "Edit User",
      uploadImage: "Upload Image",
      useGravatar: "Use Gravatar",
      removeAvatar: "Remove Avatar",
      username: "Username",
      email: "Email",
      firstName: "First Name",
      lastName: "Last Name",
      role: "Role",
      password: "New Password",
      passwordPlaceholder: "Leave empty to keep current password",
      sessionTimeout: "Inactivity timeout (minutes)",
      sessionTimeoutNone: "No automatic logout",
    },
  },
  content: {
    navigation: {
      pageTitle: "Navigations",
      dragTitle: "Drag",
      labelOverrideTitle: "Label override (empty = default)",
      remove: "Remove",
      load: "Loading…",
      noEntries: "No entries",
      typePage: "Page",
      typeUrl: "URL",
      pageTarget: "Page target",
      choosePage: "Select page…",
      add: "Add",
      addItem: "Add navigation item",
      itemType: "Navigation item type",
      urlPlaceholder: "https://… or /path",
      labelPlaceholder: "Label",
      systemTarget: "System target",
      context: "Contexts",
      area: "Areas",
      docsOwned: "Documentation routes are system-owned.",
      invalidUrl: "Enter a safe URL or relative path.",
      errorLoading: "Unable to load navigation",
      errorSaving: "Error while saving",
    },
    editor: {
      decreaseFontSize: "Decrease font size",
      increaseFontSize: "Increase font size",
      deletePage: "Delete page",
      confirmDelete: "Really delete?",
      pageTitleLabel: "Page title",
      slugLabel: "Slug",
      statusLabel: "Status",
      showTitleLabel: "Show title",
      createdBy: "Created by",
      updatedBy: "Updated by",
      updatedAt: "Updated at",
      loadingContent: "Loading content\u2026",
      preview: "Preview",
    },
    pages: {
      title: "Pages",
      newPage: "New Page",
      createTitle: "Create Page",
      fieldTitle: "Title",
      fieldSlug: "Slug",
      fieldPageType: "Page type",
      pageTypeDefault: "Default",
      pageTypeSegmented: "Segmented",
      titlePlaceholder: "Page title",
      slugPlaceholder: "page-slug",
      create: "Create",
      creating: "Creating\u2026",
      createError: "Error creating",
      confirmDeletePrefix: "Page",
      confirmDeleteSuffix: "really delete?",
      loadPages: "Loading pages\u2026",
      emptyPages: "No pages yet",
      emptyPagesHint: "Create a new page.",
      deletePageTitle: "Delete Page",
      contextRequired: "Select at least one context.",
      docsReserved: "The complete /docs namespace is system-owned.",
      contexts: {
        label: "Contexts",
        all: "All",
        frontend: "Frontend",
        developerPortal: "Developer Portal",
      },
      publication: {
        frontendTitle: "Frontend publication",
        developerPortalTitle: "Developer Portal publication",
        path: "Path",
        status: "Status",
        template: "Template",
        markdownInvalid: "Fix cross-context Markdown errors before publishing.",
        navigationDependency: "Remove the page from navigation in this context first.",
      },
      display: {
        displayMode: "Display",
        fullscreen: "Fullscreen",
        embossed: "Embossed overlay",
        translucent: "Translucent overlay",
        overlayWidth: "Width",
        widthSmall: "Small",
        widthRegular: "Regular",
        widthBig: "Big",
        contentCardStyle: "Card style",
        cardStyleDefault: "Direct",
        cardStyleRecessed: "Recessed",
      },
      segments: {
        title: "Segments",
        empty: "No segments yet.",
        labelPlaceholder: "Label",
      },
      table: {
        title: "Title",
        slug: "Slug",
        status: "Status",
        type: "Type",
        createdBy: "Created by",
        updatedAt: "Updated at",
      },
      status: { published: "Published", hidden: "Hidden", draft: "Draft" },
    },
  },
  emailTemplates: {
    listTitle: "Email Templates",
    newTemplate: "New Template",
    templateName: "Name",
    templateSubject: "Subject",
    subjectPlaceholder: "Email subject",
    bodyText: "Body",
    deleteTemplate: "Delete Template",
    deleteTemplateConfirm: "Really delete?",
    noTemplates: "No templates yet",
    noTemplatesHint: "Create a new email template.",
    systemBadge: "System",
    tableCreated: "Created",
    preview: "Preview",
    previewTitle: "Email Preview",
    blocksTitle: "Body",
    blockTypeText: "Text",
    blockTypeButton: "Button",
    blockTypeImage: "Image",
    blockTypeDivider: "Divider",
    blockTypeSpacer: "Spacer",
    buttonLabel: "Label",
    buttonUrl: "Target URL",
    imageUpload: "Upload image",
    imageUploadError: "Failed to upload image",
    imageAltText: "Alt text",
    spacerHeight: "Height (px)",
    variablesTitle: "Variables",
    variablesInsertHint: "Click to insert the placeholder at the cursor position.",
    variablesGroupSystem: "System",
    variablesGroupRecipient: "Recipient",
    variablesGroupContext: "Action",
    variablesContextUnbound: "Action variables appear once the template is bound to an action.",
    variablesDetectedTitle: "Used in this template",
    variablesDetectedEmpty: "None — this template uses no {{placeholders}}.",
    variablesUnknownWarning:
      "Unknown variables — they will not be filled when sending (typo or missing action binding).",
    exportAll: "Export all",
    importSuccess: "{n} templates imported",
    importConflictTitle: "Template \u201c{name}\u201d already exists",
    importConflictHint: "Choose how to handle the existing template.",
    sendTest: "Send test email",
    sendingTest: "Sending\u2026",
    testSent: "Test email sent to {email}",
    testFailed: "Test email failed",
    brandingTitle: "Email branding",
    brandingDescription:
      "The header/footer image, footer text and day/night background are the global default for every sent template \u2014 individual templates can override any field.",
    brandingHeaderImage: "Header image",
    brandingImageHint:
      "JPEG, PNG or WebP, max 5 MB. Scaled to 560px wide — recommended: about 1120px wide (2× for retina sharpness), wide banner format.",
    brandingFooterText: "Footer text",
    brandingFooterTextPlaceholder: "Markdown text shown below every template",
    brandingLightBackground: "Day background",
    brandingDarkBackground: "Night background",
    brandingBackgroundHint:
      "Always a gradient, optionally with an image layered on top. Shown in mail clients with a light or dark colour scheme respectively.",
    brandingGradientTop: "Gradient top",
    brandingGradientBottom: "Gradient bottom",
    brandingGradientImage: "Background image (optional)",
    brandingGradientPresets: "Previously used",
    assetPickerTitle: "Choose image",
    assetPickerChoose: "Choose image",
    assetPickerChange: "Change image",
    assetPickerUploadNew: "Upload new",
    assetPickerExisting: "Already uploaded",
    assetPickerEmpty: "No images uploaded yet",
    brandingOverrideTitle: "Branding",
    brandingOverrideHint: "Per field, use the global default or override it for this template.",
    brandingModeDefault: "Default",
    brandingModeOverride: "Override",
    brandingInheritsDefault: "Inherits global branding",
  },
  emailActions: {
    title: "Actions",
    requiredBadge: "Required",
    noActionSelected: "No action selected",
    variablesTitle: "Variables",
    variablesContextHint:
      "Event-specific variables of this action. System and recipient variables are available in every template.",
    variablesNone: "None — this action only provides system and recipient variables.",
    boundTemplatesTitle: "Bound templates",
    noTemplateBound: "No template bound",
    deletedTemplateFallback: "(deleted template)",
    assignTemplateTitle: "Bind template",
    assignTemplatePlaceholder: "Choose a template…",
    assignTemplateAction: "Bind",
    assignTemplateNoOptions: "No further templates available",
    bindErrorFallback: "Could not bind template",
  },
  errors: {
    boundary: {
      title: "Something went wrong",
      fallbackMessage: "An unexpected error occurred.",
      reload: "Go to Home",
      retry: "Try again",
    },
  },
  unsavedGuard: {
    title: "Unsaved changes",
    description: "You have unsaved changes. What would you like to do?",
    discard: "Discard",
  },
} as const;

export type DashboardCopy = typeof dashboardCopy;
